[app]
name = "bms"
author = "cn-lxy"
email = "longxinyu2021@163.com"

[server]
port = 8000

[database]
name = "web_bms"        # 数据库名
host = "127.0.0.1"      # 数据库IP地址[本地不用改]
port = 3306             # 数据库端口号
username = "root"       # 数据库用户名
password = "123456"     # 数据库密码