
### 用户注册 "/user/api/register" POST
POSt http://localhost:8080/user/api/register
Content-Type: application/json

{
  "name": "张4",
  "account": "2019002",
  "password": "123456",
  "sex": "男",
  "college": "信息...",
  "birthday": "2019-10-10"
}

### 用户登录 "/user/api/login" POST
POST http://localhost:8080/user/api/login
Content-Type: application/json

{
  "account": "2019001",
  "password": "123456"
}

### 用户登录 "/user/api/login" GET
GET http://localhost:8080/user/api/login

### 用户更改信息 "/user/api/modify" POST
POST http://localhost:8080/user/api/modify
Content-Type: application/json
  
{
  "id": 29,
  "name": "张三2"
}

### 用户借阅书籍 "user/api/borrow" POST
POST http://localhost:8080/user/api/borrow
Content-Type: application/json

{
  "userId": 29,
  "bookIsbn": "9787100017664",
  "days": 20
}

### 用户还书 "user/api/back" POST
POST http://localhost:8080/user/api/back
Content-Type: application/json

{
  "id": 6
}

### 用户查询借阅记录 "user/api/borrowed?id=1" GET
GET http://localhost:8080/user/api/borrowed?id=1&limit=10&offset=0

### 获取用户未还借阅 "user/api/not_back?id=1" GET
GET http://localhost:8080/user/api/not_back?id=1&limit=10&offset=0

### 获取用户已还借阅 "user/api/backed?id=1" GET
GET http://localhost:8080/user/api/backed?id=1&limit=10&offset=0


### 管理员登录 "/admin/api/login" POST
POST http://localhost:8080/api/admin/login
Content-Type: application/json

{
  "account": "admin",
  "password": "123456"
}

### 管理员登录-session "/admin/api/login" POST
GET http://localhost:8080/admin/api/login


### 获取所有用户 "/admin/api/manager/user/getall?limit=10&offset=0" GET
GET http://localhost:8080/admin/api/manager/user/getall?limit=10&offset=0

### 搜索用户 "/api/admin/manager/user/search?by=0&key=小明"
GET http://localhost:8080/api/admin/manager/user/search?by=3&key=1&limit=1&offset=0 HTTP/1.1

### 更新用户信息 "/admin/api/manager/user/update" POST
POST http://localhost:8080/admin/api/manager/user/update
Content-Type: application/json

{
  "id": 29,
  "name": "张三1"
}

### 删除用户 "/admin/api/manager/user/delete" GET
GET http://localhost:8080/admin/api/manager/user/delete?id=30

### 获取多本图书信息 ”admin/api/manager/book/getbooks?limit=10&offset=0" GET
GET http://localhost:8080/admin/api/manager/book/getbooks?by=0&limit=10&offset=0
### 
GET http://localhost:8080/admin/api/manager/book/getbooks?by=1&typeid=3&limit=10&offset=0 

### 搜索图书 "/admin/api/manager/book/search?by={0,1}&value={isbn,name}" GET
### isbn: 9787010009223
GET http://localhost:8080/api/admin/manager/book/search?by=0&value=9787010009223
### name: 围城
GET http://localhost:8080/admin/api/manager/book/search?by=1&value=%E5%9B%B4%E5%9F%8E

### 新建图书 "/admin/api/manager/book" POST
POST http://localhost:8080/api/admin/manager/book
Content-Type: application/json

{
  "isbn": "9787100017666",
  "name": "inset图书",
  "type_id": 1,
  "author": "test",
  "public": "test出版社",
  "public_date": "2022-07",
  "stock": 100
}

### 删除书籍 "/admin/api/manager/book/delete?isbn=xx" GET
GET http://localhost:8080/admin/api/manager/book/delete?isbn=1

### 更新书籍 "/admin/api/manager/book/update" POST
POST http://localhost:8080/admin/api/manager/book/update
Content-Type: application/json

{
  "isbn": "9787100017666",
  "name": "inset图书",
  "type_id": 2,
  "author": "test",
  "public": "test出版社",
  "public_date": "2022-07",
  "stock": 100
}

### 获取借阅记录信息 "/admin/api/manager/borrow?limit=xx&&offset=xx" GET
GET http://localhost:8080/admin/api/manager/borrow?limit=10&offset=0

### 获取用户借阅信息 "/admin/api/manager/borrow/{userid}?type=xx&limit=xx&offset=xx" GET
### 全部借阅
GET http://localhost:8080/admin/api/manager/borrow/u/1?type=1&limit=10&offset=0
### 未还借阅
GET http://localhost:8080/admin/api/manager/borrow/u/1?type=2&limit=10&offset=0
### 已还借阅
GET http://localhost:8080/admin/api/manager/borrow/u/1?type=3&limit=10&offset=0


### 获取被借书籍用户 "/admin/api/manager/borrow/b/9787010009223" GET
GET http://localhost:8080/admin/api/manager/borrow/b/9787010009223